#! /usr/bin/env yml-docker-compose.sh
version: '3'
services:

  # harvest:
  #   volumes:
  #     - ./io:/io

  vivo-solr:
    image: ucdlib/vivo-solr:master
    volumes:
      - vivo-solr-data:/var/solr/data

  discovery-solr:
    image: ucdlib/scholars-discovery-solr:master
    volumes:
      - discovery-solr-data:/var/solr/data

  vivo:
    image: ucdlib/rp-ucd-vivo:master
    volumes:
      - vivo-content-tdb:/usr/local/vivo/home/tdbContentModels
      - vivo-configuration-tdb:/usr/local/vivo/home/tdbModels
      - vivo-upgrade-data:/usr/local/vivo/home/upgrade
      - vivo-uploads-data:/usr/local/vivo/home/uploads
    depends_on:
      - vivo-solr

  discovery-api:
    image: ucdlib/rp-ucd-scholars-discovery:master

  gateway:
    image: ucdlib/rp-ucd-service-gateway:master
    ports:
      - ${HOST_PORT:-8080}:8080
    restart: on-failure

volumes:
  harvest-data:
  discovery-solr-data:
  vivo-solr-data:
  vivo-configuration-tdb:
  vivo-content-tdb:
  vivo-upgrade-data:
  vivo-uploads-data:
