version: '3'
services:

  zookeeper:
    image: zookeeper:3.6
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  fuseki:
    image: ucdlib/rp-ucd-fuseki:jena-3.15.0-c-0.0.3
    env_file:
      - .env
    environment:
      - ADMIN_PASSWORD=${FUSEKI_PASSWORD}
    volumes:
      - fuseki-data:/fuseki

  kafka:
    image: bitnami/kafka:2.5.0
    env_file:
      - .env
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes: 
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  redis:
    image: redis:6.0.5
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  client:
    image: ucdlib/rp-ucd-client:master
    env_file:
      - .env
    restart: on-failure

  gateway:
    image: ucdlib/rp-ucd-gateway:master
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-8080}:${HOST_PORT:-8080}
    restart: on-failure

  auth:
    image: ucdlib/rp-ucd-auth-cas:master
    env_file:
      - .env
    restart: on-failure

  api:
    image: ucdlib/rp-ucd-api:master
    env_file:
      - .env
    restart: on-failure

  debouncer:
    image: ucdlib/rp-ucd-kafka-debouncer:master
    env_file:
      - .env
    restart: on-failure

  indexer:
    image: ucdlib/rp-ucd-es-indexer:master
    env_file:
      - .env
    restart: on-failure

volumes:
  es-data:
  fuseki-data:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data:
