version: '3'
services:

  zookeeper:
    image: zookeeper:3.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  fuseki:
    image: gcr.io/ucdlib-pubreg/rp-ucd-fuseki:1.3.3
    env_file:
      - .env
    volumes:
      - fuseki-data:/fuseki
    ports: # still exposed for admin access
      - ${FUSEKI_HOST_PORT:-8081}:3030

  harvest:
    image: gcr.io/ucdlib-pubreg/rp-ucd-harvest:dev
    env_file:
      - .env
    volumes:
       - harvest-data:/var/lib/harvest
    command: tail -f /dev/null

  kafka:
    image: bitnami/kafka:2.5.0
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  redis:
    image: redis:6.0.5
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  client:
    image: gcr.io/ucdlib-pubreg/rp-ucd-client:sandbox
    env_file:
      - .env
    restart: on-failure

  gateway:
    image: gcr.io/ucdlib-pubreg/rp-ucd-gateway:sandbox
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-8080}:3000
    restart: on-failure

  auth:
    image: gcr.io/ucdlib-pubreg/rp-ucd-auth-cas:sandbox
    env_file:
      - .env
    environment:
      - CAS_URL=${CAS_URL:-https://ssodev.ucdavis.edu/cas}
    restart: on-failure

  api:
    image: gcr.io/ucdlib-pubreg/rp-ucd-api:sandbox
    env_file:
      - .env
    restart: on-failure

  debouncer:
    image: gcr.io/ucdlib-pubreg/rp-ucd-kafka-debouncer:sandbox
    env_file:
      - .env
    restart: on-failure

  indexer:
    image: gcr.io/ucdlib-pubreg/rp-ucd-es-indexer:sandbox
    env_file:
      - .env
    ports:
      - ${INDEXER_HOST_PORT:-8082}:3000
    restart: on-failure

  models:
    image: gcr.io/ucdlib-pubreg/rp-ucd-es-models:sandbox
    env_file:
      - .env
    restart: on-failure

volumes:
  es-data:
  fuseki-data:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data:
  harvest-data:
