#! /usr/bin/env yml-docker-compose.sh
version: '3'
services:

  harvest:
    image: ucdlib/rp-ucd-vivo-harvester:develop
    volumes:
      - ./io:/io
      - ./harvester-raw-records:/usr/local/vivo/harvester/data/raw-records
    command: bash -c "tail -f /dev/null"

  vivo-solr:
    image: ucdlib/vivo-solr:master
    volumes:
      - vivo-solr-data:/var/solr/data

  discovery-solr:
    image: ucdlib/scholars-discovery-solr:master
    volumes:
      - discovery-solr-data:/var/solr/data

  vivo:
    image: ucdlib/rp-ucd-vivo:master
    volumes:
      - vivo-content-tdb:/usr/local/vivo/home/tdbContentModels
      - vivo-configuration-tdb:/usr/local/vivo/home/tdbModels
      - vivo-upgrade-data:/usr/local/vivo/home/upgrade
      - vivo-uploads-data:/usr/local/vivo/home/uploads
    env_file:
      - .env
    environment:
      - VIVO_SOLR_HOSTNAME=vivo-solr
    depends_on:
      - vivo-solr

  discovery-api:
    image: ucdlib/rp-ucd-scholars-discovery:master
    environment:
      - APP_URL=${APP_URL:-http://localhost:8080}
      - DISCOVERY_SOLR_HOSTNAME=discovery-solr
      - VIVO_BASE_URL=http://vivo:8080/vivo
    depends_on:
      - discovery-solr

  client:
    image: ucdlib/rp-ucd-client:master

  gateway:
    image: ucdlib/rp-ucd-service-gateway:master
    ports:
      - ${HOST_PORT:-8080}:8080
    restart: on-failure

volumes:
  harvest-data:
  discovery-solr-data:
  vivo-solr-data:
  vivo-configuration-tdb:
  vivo-content-tdb:
  vivo-upgrade-data:
  vivo-uploads-data:
