#! /usr/bin/env yml-docker-compose.sh
version: '3'
services:

  vivo-solr:
    image: ucdlib/vivo-solr:master
    volumes:
      - vivo-solr-data:/var/solr/data

  vivo:
    image: ucdlib/rp-ucd-vivo:master
    volumes:
      - vivo-content-tdb:/usr/local/vivo/home/tdbContentModels
      - vivo-configuration-tdb:/usr/local/vivo/home/tdbModels
      - vivo-upgrade-data:/usr/local/vivo/home/upgrade
      - vivo-uploads-data:/usr/local/vivo/home/uploads
      - ./vivo-docker-entrypoint.sh:/docker-entrypoint.sh
      - ./wait-for-it.sh:/wait-for-it.sh
    env_file:
      - .env
    environment:
      - VIVO_SOLR_HOSTNAME=vivo-solr
    depends_on:
      - vivo-solr
    ports:
      - 8080:8080

volumes:
  vivo-solr-data:
  vivo-configuration-tdb:
  vivo-content-tdb:
  vivo-upgrade-data:
  vivo-uploads-data:
