 apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvest-deployment
spec:
  selector:
    matchLabels:
      app: harvest
  template:
    metadata:
      labels:
        app: harvest
    spec:
      containers:
      - name: harvest
        image: {{HARVEST_IMAGE_NAME}}:{{HARVEST_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        # TODO: change back when proper debug in place
        - name: LOG_LEVEL
          value: "info"
        - name: EXPIRE_DIR_DEPTH
          value: "4"
        resources:
          limits:
            memory: "400Mi"
            cpu: "400m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
      - name: expire-rev
        image: gcr.io/ucdlib-pubreg/krm-expire:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        # TODO: change back when proper debug in place
        - name: LOG_LEVEL
          value: "info"
        - name: EXPIRE_DIR_DEPTH
          value: "4"
        - name: EXPIRE_DIRECTION
          value: "reverse"
        - name: EXPIRE_DIR_DEPTH
          value: "4"
        resources:
          limits:
            memory: "400Mi"
            cpu: "400m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false