apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_SEARCH_TAG}}
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: zookeeper-data-persistent-storage
          mountPath: /data
        - name: zookeeper-datalog-persistent-storage
          mountPath: /data
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
      nodeSelector:
        intendedfor: default-pool
  # TODO: look to switch to: 
  # https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
    name: zookeeper-datalog-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi