#! /bin/bash

###
# Push docker image and $DOCKER_CACHE_TAG (currently :latest) tag to docker hub
###

set -e
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $ROOT_DIR/..
source config.sh

docker push $CLIENT_IMAGE_NAME:$CLIENT_TAG
docker tag $CLIENT_IMAGE_NAME:$CLIENT_TAG $CLIENT_IMAGE_NAME:$DOCKER_CACHE_TAG

docker push $NODE_UTILS_IMAGE_NAME:$VESSEL_TAG
docker tag $NODE_UTILS_IMAGE_NAME:$VESSEL_TAG $NODE_UTILS_IMAGE_NAME:$DOCKER_CACHE_TAG

docker push $DEBOUNCER_IMAGE_NAME:$VESSEL_TAG
docker tag $DEBOUNCER_IMAGE_NAME:$VESSEL_TAG $DEBOUNCER_IMAGE_NAME:$DOCKER_CACHE_TAG

docker push $INDEXER_IMAGE_NAME:$VESSEL_TAG
docker tag $INDEXER_IMAGE_NAME:$VESSEL_TAG $INDEXER_IMAGE_NAME:$DOCKER_CACHE_TAG

docker push $API_IMAGE_NAME:$VESSEL_TAG
docker tag $API_IMAGE_NAME:$VESSEL_TAG $API_IMAGE_NAME:$DOCKER_CACHE_TAG

docker push $GATEWAY_IMAGE_NAME:$VESSEL_TAG
docker tag $GATEWAY_IMAGE_NAME:$VESSEL_TAG $GATEWAY_IMAGE_NAME:$DOCKER_CACHE_TAG

for image in "${ALL_DOCKER_BUILD_IMAGES[@]}"; do
  docker push $image:$DOCKER_CACHE_TAG || true
done