version: '3'
services:

  zookeeper:
    image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_TAG}}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  fuseki:
    image: {{FUSEKI_IMAGE_NAME}}:{{FUSEKI_TAG}}
    env_file:
      - .env
    volumes:
      - fuseki-data:/fuseki
    ports:
      - ${FUSEKI_HOST_PORT:-8081}:3030

  kafka:
    image: {{KAFKA_IMAGE_NAME}}:{{KAFKA_TAG}}
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"
    ports:
      - 9092:9092

  kafka-init:
    image: {{KAFKA_INIT_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/kafka-init/init.sh:/init.sh
    depends_on:
      - "zookeeper"

  redis:
    image: {{REDIS_IMAGE_NAME}}:{{REDIS_TAG}}
    volumes:
      - redis-data:/data

  elasticsearch:
    image: {{ELASTIC_SEARCH_IMAGE_NAME}}:{{ELASTIC_SEARCH_TAG}}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  client:
    image: {{CLIENT_IMAGE_NAME}}:{{CLIENT_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/index.js:/server/index.js
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/lib:/server/lib
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/controllers:/server/controllers
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/client:/server/client
    # command: bash -c "tail -f /dev/null"

  gateway:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    environment:
      - PRIVATE_SERVER=${PRIVATE_SERVER:-false}
    ports:
      - ${HOST_PORT:-8080}:3000
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
    command: npm run gateway
    # command: bash -c "tail -f /dev/null"

  auth:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    environment:
      - CAS_URL=${CAS_URL:-https://ssodev.ucdavis.edu/cas}
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
    command: npm run auth-cas
    # command: bash -c "tail -f /dev/null"

  api:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
    ports:
      - ${API_HOST_PORT:-8083}:3000
    command: npm run api
    # command: bash -c "tail -f /dev/null"

  indexer:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
      - ./service-account.json:/etc/service-account.json
    ports:
      - ${INDEXER_HOST_PORT:-8082}:3000
    command: npm run es-indexer
    # command: bash -c "tail -f /dev/null"

  status:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
    command: npm run status
    # command: bash -c "tail -f /dev/null"

  gcs:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/service-account.json
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
      - ./service-account.json:/etc/service-account.json
    ports:
      - ${INDEXER_HOST_PORT:-8085}:3000
    # command: npm run gcs
    command: bash -c "tail -f /dev/null"

  models:
    image: {{NODE_SERVICES_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/lib:/aggie-experts/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/node-services/services:/aggie-experts/services
      - ./service-account.json:/etc/service-account.json
    ports:
      - ${MODEL_HOST_PORT:-8084}:3000
    command: npm run es-models
    # command: bash -c "tail -f /dev/null"

volumes:
  es-data:
  fuseki-data:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data:
  harvest-xslt-data:
  harvest-data:
