version: '3'
services:

  zookeeper:
    image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_TAG}}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  fuseki:
    image: {{FUSEKI_IMAGE_NAME}}:{{FUSEKI_TAG}}
    env_file:
      - .env
    volumes:
      - fuseki-data:/fuseki
    ports:
      - ${FUSEKI_HOST_PORT:-8081}:3030

  harvest:
    image: {{HARVEST_IMAGE_NAME}}:{{HARVEST_TAG}}
    env_file:
      - .env
    volumes:
       - harvest-xslt-data:/usr/local/vivo/harvester/data
       - harvest-data:/var/lib/harvest
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/lib:/usr/local/lib/harvest
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/ucdid:/usr/local/bin/ucdid
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/cdl:/usr/local/bin/cdl
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/harvest:/usr/local/bin/harvest
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/lib/node/lib:/service/lib
       - ../{{REPOSITORY_DIR}}/{{HARVEST_REPO_NAME}}/lib/node/index.js:/service/index.js
    command: tail -f /dev/null

  kafka:
    image: {{KAFKA_IMAGE_NAME}}:{{KAFKA_TAG}}
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"
    ports:
      - 9092:9092

  redis:
    image: {{REDIS_IMAGE_NAME}}:{{REDIS_TAG}}
    volumes:
      - redis-data:/data

  elasticsearch:
    image: {{ELASTIC_SEARCH_IMAGE_NAME}}:{{ELASTIC_SEARCH_TAG}}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  client:
    image: {{CLIENT_IMAGE_NAME}}:{{CLIENT_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/index.js:/server/index.js
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/lib:/server/lib
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/controllers:/server/controllers
      - ../{{REPOSITORY_DIR}}/{{CLIENT_REPO_NAME}}/client:/server/client
    # command: bash -c "tail -f /dev/null"

  gateway:
    image: {{GATEWAY_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    environment:
      - PRIVATE_SERVER=${PRIVATE_SERVER:-false}
    ports:
      - ${HOST_PORT:-8080}:3000
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/gateway/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/gateway/controllers:/service/controllers
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/gateway/lib:/service/lib
    # command: bash -c "tail -f /dev/null"

  auth:
    image: {{AUTH_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    environment:
      - CAS_URL=${CAS_URL:-https://ssodev.ucdavis.edu/cas}
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/auth-cas/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/auth-cas/controller.js:/service/controller.js
    # command: bash -c "tail -f /dev/null"

  api:
    image: {{API_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/api/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/api/lib:/service/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/api/controllers:/service/controllers
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/api/models:/service/models
    ports:
      - ${API_HOST_PORT:-8083}:3000
    # command: bash -c "tail -f /dev/null"

  debouncer:
    image: {{DEBOUNCER_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/debouncer/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/debouncer/lib:/service/lib
    # command: bash -c "tail -f /dev/null"

  indexer:
    image: {{INDEXER_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/es-indexer/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/es-indexer/lib:/service/lib
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/es-indexer/controllers:/service/controllers
    ports:
      - ${INDEXER_HOST_PORT:-8082}:3000
      # command: bash -c "tail -f /dev/null"

  models:
    image: {{MODEL_IMAGE_NAME}}:{{VESSEL_TAG}}
    env_file:
      - .env
    volumes:
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/es-models/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/es-models/default:/service/default
      - ../{{REPOSITORY_DIR}}/{{VESSEL_REPO_NAME}}/es-models/model:/service/model
    ports:
      - ${MODEL_HOST_PORT:-8084}:3000
    # command: bash -c "tail -f /dev/null"

volumes:
  es-data:
  fuseki-data:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data:
  harvest-xslt-data:
  harvest-data:
